services:
  - type: web
    name: pearls-aqi-predictor
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run 3_app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: AQICN_API_TOKEN
        sync: false
      - key: HOPSWORKS_API_KEY
        sync: false
